language: python
python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run black app
  - pipenv run isort app
  - pipenv run flake8 app
  - pipenv run mypy app
