services:
  - docker

before_install:
  - docker run -d -p 8529:8529 -e ARANGO_NO_AUTH=1 arangodb/arangodb:3.5.1
  - docker ps -a

language: python
python:
  - '3.7'
install:
  - cd server
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run black .
  - pipenv run isort -rc .
  - pipenv run flake8 api tests
  - pipenv run mypy .
  - pipenv run python -m pytest
