language: python
python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run black .
  - pipenv run isort -rc .
  - pipenv run flake8 api tests
  - pipenv run mypy .
  - pipenv run python -m pytest
